### ISSUE TITLE
Do you even PSR?

### ISSUE THREAD

**Issue by patkar** [essence/essence#101]
Sadly a 3.0.0 is already released. But maybe you will think about PSR-1 and PSR-2 for the next major release. Uppercase variables and properties starting with underscores are simply ugly.

The usage of a common code style in the code and code quality in general is an important criteria for using the code or not for many users.

**Comment by felixgirault** [comment]
It is unlikely that essence will ever support PSR-2. To use the same kind of argument, I should say that among other things, I find spaces for indentation extremely ugly and stupid.
However, I'm really trying to improve the overall quality of the code with each release.
I don't think that the naming of private variables and functions should restrain you from using a lib.

**Comment by patkar** [comment]
It's about interoperability, not what you personally like. Any library using PSR-2 is better for new collaborators, because they don't have to break their head about code style, they know it already from all other libraries and packages among the PHP world.

**Comment by felixgirault** [comment]
I agree about interoperability, but essence's coding style is not so far from PSR.

Also, I would give the word "interoperability" another meaning. A chunk of code doesn't play nice with others because they all put opening braces on a new line, but because it's purpose is well defined, because it can be easily replaced or extended. This is interoperability to me.

Finally, strictly about coding style, I'm not sure that developers should follow a standard they don't like, just because it was written by some kind of authority. To take the previous example, I think there is no strong reason why I should use space instead of tabs if I find it annoying.

**Comment by patkar** [comment]
How sad a fate!
