### ISSUE TITLE
Guide to Create Custom Providers

### ISSUE THREAD

**Issue by touhonoob** [essence/essence#90]
Hi, Thanks for the great library.
Is there a guide to create custom providers without oembed endpoints?

**Comment by felixgirault** [comment]
Hi, and thank you for using it ;)
There is no such guide but it should be fairly simple.

First, you'll have to create a subclass of `Provider` (https://github.com/felixgirault/essence/blob/master/lib/Essence/Provider.php), and implement the `_embed()` method.
This method takes an URL and returns a Media object containing all the extracted properties.
You can look at the default providers to see how it should look like.

Then, you'll have to tell Essence about your provider :

```
$Essence = Essence\Essence::instance([
    'MyProvider' => function() {
        return new My\Provider();
    }
]);
```

And finally, configure the provider :

```
$Essence = Essence\Essence::instance([
    'MyProvider' => /* ... */
    'providers' => [
        'MyProvider' => [
            'class' => 'MyProvider',
            'filter' => '~myprovider\.com/video/.*~i'
        ],
    ]
]);
```

Sadly, I just realized that initializing Essence like that will only load your custom provider.
So the best way to add it to the default list would be to copy it somewhere from https://github.com/felixgirault/essence/blob/master/lib/providers.php, add your custom config to it, and pass this file to Essence :

```
$Essence = Essence\Essence::instance([
    'MyProvider' => /* ... */
    'providers' => '/path/to/the/providers/config.php'
]);
```

I hope everything is understandable, otherwise I'm open for other questions ;)
